[package]
name = "cccb-display"
version = "0.1.0"
edition = "2021"
authors = ["patte <p@tte.io>"]

[dependencies]
dotenv = "0.15.0"
image = "^0.25"

[[example]]
name = "simple"
path = "src/examples/simple.rs"

[[example]]
name = "loop"
path = "src/examples/loop.rs"
